# Generated by Django 3.0.3 on 2020-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('groceries', 'groceries'), ('salary', 'salary'), ('transfer', 'transfer'), ('rent', 'rent'), ('savings', 'savings'), ('other', 'other')], max_length=20),
        ),
    ]
